name: Docker
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build Docker Image
        run: |
          echo "Building image"
          docker build -t ghcr.io/depthbomb/splash:latest .

          echo "Tagging image"
          docker tag ghcr.io/depthbomb/splash:latest ghcr.io/depthbomb/splash:${{ github.sha }}

      - name: Push Docker Image as SHA
        run: docker push ghcr.io/depthbomb/splash:${{ github.sha }}

      - name: Push Docker Image as Tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          docker tag ghcr.io/depthbomb/splash:latest ghcr.io/depthbomb/splash:${{ github.ref_name }}
          docker push ghcr.io/depthbomb/splash:${{ github.ref_name }}

      - name: Push Docker Image as latest
        if: ${{ github.ref == 'refs/heads/master' }}
        run: docker push ghcr.io/depthbomb/splash:latest
